version: '3.8'
services:
  notification-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: notification
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sam
    ports:
      - "5432:5432"
    networks:
      - backend
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
networks:
  backend:
